### ISSUE TITLE
Could you provide the download address for the dataset？

### ISSUE THREAD

**Issue by smilebook5** [nalinrajendran/eco-agri-bot#2]
Could you provide the download address for the dataset？I can't find it.

**Comment by HarxSan** [comment]
Did you find the dataset address , if so do ping it.

**Comment by Chhavinder058** [comment]
Please do share the dataset link for easy accessibility.
Thank you!

**Comment by nalinrajendran** [comment]
Hi folks, I don have the post processed dataset handy, it was not more than
the pdfs available from TNAU official sites.. I scraped them all and
transformed it.
